#include "CobDispatchTable.h"

#include "hook/hook.h"
#include "iddrawsurface.h"

#include <cstdint>
#include <cstring>
#include <memory>

// ===========================================================================
// Verified anchors. Re-derive and cross-check all of these against the shipped
// binary with `python ai-reference/tools/exe/cob_dispatch.py --verify` before
// trusting a change to any of them -- see COB_DISPATCH_PROJECT.md SS1 (the B1
// gate). Addresses are TotalA.exe Escalation GOLD 10.1/10.2 (the two builds are
// code-identical -- README_SYMBOLS.md Finding 1), no ASLR.
// ===========================================================================

namespace {

constexpr std::uintptr_t kWindowAddr    = 0x4B0E69;   // splice window start
constexpr std::size_t    kWindowLen     = 38;         // splice window length, bytes
constexpr std::uintptr_t kErrorPath     = 0x4B1B60;   // vanilla's "unknown opcode" handler
constexpr std::uintptr_t kVmLo          = 0x4B0DA0;   // UnitScript_ExecSlot entry
constexpr std::uintptr_t kVmHi          = 0x4B1C00;   // UnitScript_AdvancePieceAnims entry

// The jz this patch writes lands at the address vanilla's first ladder node
// occupied (the "cmp edx,0x10002000" in the original bytes). BuildPatchBytes()
// computes this address from the byte layout as it writes each instruction, and
// Install() asserts the result matches this constant before patching anything --
// if it ever does not, the window moved and every offset here needs re-deriving
// from the binary, not just this one number.
constexpr std::uintptr_t kExpectedJzAddr = 0x4B0E71;

// Original bytes at kWindowAddr: `mov edx,ebx` / `and edx,0x100FF000` / the first
// ladder node's `cmp/ja/je/cmp/jne`. Asserted byte-for-byte before every install;
// COB_DISPATCH_PROJECT.md SS27.4 and ENGINE_NOTES.md SS27.4/27.6.
constexpr unsigned char kOriginalBytes[kWindowLen] = {
    0x8B, 0xD3, 0x81, 0xE2, 0x00, 0xF0, 0x0F, 0x10, 0x81, 0xFA, 0x00, 0x20, 0x00,
    0x10, 0x0F, 0x87, 0x6F, 0x01, 0x00, 0x00, 0x0F, 0x84, 0xA9, 0x00, 0x00, 0x00,
    0x81, 0xFA, 0x00, 0x10, 0x00, 0x10, 0x0F, 0x85, 0xD1, 0x0C, 0x00, 0x00,
};

// TABLE[i] = handler(0x10000000 | i<<12), else kErrorPath. 57 real entries, 199
// pointing at the error path. Generated by, and verified byte-for-byte identical
// to, cob_jump_table_256.json via an independent control-flow re-derivation of
// the binary (`cob_dispatch.py --verify`, "ALL CHECKS PASSED", 2026-08-21). Do
// not hand-edit -- regenerate with `cob_dispatch.py --dump` and re-verify.
const void* g_table[256] = {
    (void*)0x4B1B60, (void*)0x4B0E8F, (void*)0x4B0F2C, (void*)0x4B100A,
    (void*)0x4B1086, (void*)0x4B10E9, (void*)0x4B10EF, (void*)0x4B111E,
    (void*)0x4B1124, (void*)0x4B1153, (void*)0x4B1185, (void*)0x4B11B6,
    (void*)0x4B1210, (void*)0x4B1288, (void*)0x4B128E, (void*)0x4B12BD,
    (void*)0x4B1B60, (void*)0x4B12E6, (void*)0x4B1323, (void*)0x4B134A,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B139C, (void*)0x4B13E8, (void*)0x4B140E,
    (void*)0x4B1469, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B148F, (void*)0x4B14AC, (void*)0x4B14DF,
    (void*)0x4B14FD, (void*)0x4B1531, (void*)0x4B154E, (void*)0x4B1581,
    (void*)0x4B159E, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B15C9, (void*)0x4B15F7, (void*)0x4B163C,
    (void*)0x4B168B, (void*)0x4B16C4, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B16DB, (void*)0x4B1713, (void*)0x4B1735,
    (void*)0x4B176D, (void*)0x4B178F, (void*)0x4B17C7, (void*)0x4B17E9,
    (void*)0x4B1829, (void*)0x4B1863, (void*)0x4B1896, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B18B0, (void*)0x4B191D, (void*)0x4B1984,
    (void*)0x4B19C7, (void*)0x4B19D0, (void*)0x4B1A4C, (void*)0x4B1A75,
    (void*)0x4B1B08, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B1F, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1BB9, (void*)0x4B1B92,
    (void*)0x4B1B7D, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60,
    (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60, (void*)0x4B1B60
};

// Buffer for the 38 replacement bytes. Namespace-scope, not a local of Install():
// SingleHook(..., INLINE_UNPROTECTEVINMENT, ...) stores this pointer as-is rather
// than copying it and may re-read it for the lifetime of g_hook, so it has to
// outlive Install()'s stack frame.
unsigned char g_patchBytes[kWindowLen];

std::unique_ptr<SingleHook> g_hook;

// Step 2 of the verification plan (COB_DISPATCH_PROJECT.md SS7): every table
// entry must land inside the VM or be the error path. Checked at Install() time
// against the actual array above, not asserted once and trusted forever.
bool TableEntriesInRange()
{
    for (int i = 0; i < 256; ++i)
    {
        const std::uintptr_t h = reinterpret_cast<std::uintptr_t>(g_table[i]);
        if (h != kErrorPath && (h < kVmLo || h >= kVmHi))
            return false;
    }
    return true;
}

// Counts error-path vs handler entries in g_table, for the install-time report
// below. Trusts nothing computed earlier in this file -- recounts from the
// live array, the same way TableEntriesInRange() does, so a corruption between
// the pre-install check and here (there is no code path that could cause one,
// but the report exists precisely so we do not have to trust "there is no
// code path") would show up as counts that do not sum to 256.
void CountTableEntries(int& errorPathCount, int& handlerCount, int& outOfRangeCount)
{
    errorPathCount = 0;
    handlerCount = 0;
    outOfRangeCount = 0;
    for (int i = 0; i < 256; ++i)
    {
        const std::uintptr_t h = reinterpret_cast<std::uintptr_t>(g_table[i]);
        if (h == kErrorPath)
            ++errorPathCount;
        else if (h >= kVmLo && h < kVmHi)
            ++handlerCount;
        else
            ++outOfRangeCount;
    }
}

// SingleHook::Hook() is void and never surfaces a failed write, so this reads
// the window straight back out of live memory (like checkPatchState() does
// from outside the process, just from inside it) and logs one line to
// tdrawlog.txt confirming the bytes match, the table pointer is correct, and
// the table sums to 256 entries. Not a replacement for checkPatchState() -- a
// bug that corrupts both the write and this readback the same way would pass
// silently -- but it catches a VirtualProtect failure or a torn write with
// zero manual steps, on every run.
void LogInstallReport()
{
    const unsigned char* live = reinterpret_cast<const unsigned char*>(kWindowAddr);

    bool matchesPatch = (std::memcmp(live, g_patchBytes, kWindowLen) == 0);
    bool stillOriginal = (std::memcmp(live, kOriginalBytes, kWindowLen) == 0);

    if (!matchesPatch)
    {
        IDDrawSurface::OutptFmtTxt(
            "[CobDispatchTable] SELF-CHECK FAILED: live bytes at 0x%X do not match "
            "what was written (%s). The hook call returned normally but the write "
            "did not land as intended -- do not trust this session's dispatch "
            "behaviour. Report this.",
            (unsigned int)kWindowAddr, stillOriginal ? "window is unmodified" : "window holds something else");
        return;
    }

    // Offset re-derived from BuildPatchBytes()'s own byte layout (23 bytes
    // precede this dword) -- NOT copied from checkPatchState()'s Lua, whose
    // readBytes() is 1-indexed and would be off by one here. Do not change
    // this back to +24.
    std::uint32_t liveTableAddr = 0;
    std::memcpy(&liveTableAddr, live + 23, 4);
    const std::uint32_t expectTableAddr =
        static_cast<std::uint32_t>(reinterpret_cast<std::uintptr_t>(&g_table[0]));

    int errorPathCount = 0, handlerCount = 0, outOfRangeCount = 0;
    CountTableEntries(errorPathCount, handlerCount, outOfRangeCount);

    if (liveTableAddr != expectTableAddr || outOfRangeCount != 0)
    {
        IDDrawSurface::OutptFmtTxt(
            "[CobDispatchTable] SELF-CHECK FAILED: live jmp table pointer=0x%X "
            "expected=0x%X, out-of-range table entries=%d (expected 0). Report this.",
            liveTableAddr, expectTableAddr, outOfRangeCount);
        return;
    }

    IDDrawSurface::OutptFmtTxt(
        "[CobDispatchTable] self-check OK: PATCHED, jump table active at 0x%X, "
        "256/256 entries valid (%d error-path, %d handlers). Live bytes verified "
        "readback match, in-process.",
        liveTableAddr, errorPathCount, handlerCount);
}

// Writes the 27-byte replacement sequence plus int3 padding into `patch`, and
// returns the address of the jz instruction it wrote -- computed from the byte
// layout as it goes, not hardcoded, so a change to any instruction above it is
// self-checking (Install() compares the result against kExpectedJzAddr).
//
//   mov   edx, ebx                       ; 2
//   test  ebx, 0x10000000                ; 6   opcode-space bit
//   jz    kErrorPath                     ; 6   -> vanilla error path
//   shr   edx, 12                        ; 3
//   movzx edx, dl                        ; 3   edx = 0..255
//   jmp   dword ptr [g_table + edx*4]    ; 7
//   int3  x 11                           ; 11  padding to fill the 38-byte window
std::uintptr_t BuildPatchBytes(unsigned char (&patch)[kWindowLen])
{
    std::size_t off = 0;

    patch[off++] = 0x8B; patch[off++] = 0xD3;                          // mov edx, ebx

    patch[off++] = 0xF7; patch[off++] = 0xC3;                          // test ebx, imm32
    {
        const std::uint32_t opcodeSpaceBit = 0x10000000u;
        std::memcpy(&patch[off], &opcodeSpaceBit, 4);
        off += 4;
    }

    const std::uintptr_t jzAddr = kWindowAddr + off;
    patch[off++] = 0x0F; patch[off++] = 0x84;                          // jz rel32
    {
        const std::uintptr_t jzEnd = kWindowAddr + off + 4;
        const std::int32_t rel = static_cast<std::int32_t>(kErrorPath - jzEnd);
        std::memcpy(&patch[off], &rel, 4);
        off += 4;
    }

    patch[off++] = 0xC1; patch[off++] = 0xEA; patch[off++] = 0x0C;     // shr edx, 12
    patch[off++] = 0x0F; patch[off++] = 0xB6; patch[off++] = 0xD2;     // movzx edx, dl

    patch[off++] = 0xFF; patch[off++] = 0x24; patch[off++] = 0x95;     // jmp [imm32+edx*4]
    {
        const std::uint32_t tableAddr =
            static_cast<std::uint32_t>(reinterpret_cast<std::uintptr_t>(&g_table[0]));
        std::memcpy(&patch[off], &tableAddr, 4);
        off += 4;
    }

    while (off < kWindowLen)
        patch[off++] = 0xCC;                                          // int3 padding

    return jzAddr;
}

} // namespace

namespace CobDispatchTable {

void Install()
{
    if (g_hook)
        return;   // idempotent

    if (!TableEntriesInRange())
    {
        IDDrawSurface::OutptTxt(
            "[CobDispatchTable] INTERNAL ERROR: a jump-table entry points outside "
            "the VM region -- refusing to patch. This is a bug in the table, not a "
            "build mismatch; report it.");
        return;
    }

    const unsigned char* live = reinterpret_cast<const unsigned char*>(kWindowAddr);
    if (std::memcmp(live, kOriginalBytes, kWindowLen) != 0)
    {
        IDDrawSurface::OutptTxt(
            "[CobDispatchTable] splice-window signature mismatch at 0x4B0E69 -- "
            "this build's COB VM does not match Escalation GOLD 10.1/10.2. Leaving "
            "the original dispatch ladder untouched.");
        return;
    }

    const std::uintptr_t jzAddr = BuildPatchBytes(g_patchBytes);
    if (jzAddr != kExpectedJzAddr)
    {
        IDDrawSurface::OutptTxt(
            "[CobDispatchTable] INTERNAL ERROR: computed jz address does not match "
            "the expected 0x4B0E71 -- refusing to patch. This is a bug in the "
            "offset math, not a build mismatch; report it.");
        return;
    }

    g_hook = std::make_unique<SingleHook>(
        static_cast<unsigned int>(kWindowAddr), static_cast<DWORD>(kWindowLen),
        INLINE_UNPROTECTEVINMENT, g_patchBytes);
    FlushInstructionCache(GetCurrentProcess(),
        reinterpret_cast<LPCVOID>(kWindowAddr), kWindowLen);

    IDDrawSurface::OutptTxt(
        "[CobDispatchTable] installed: opcode dispatch now uses a 256-entry jump "
        "table instead of the linear compare ladder.");

    LogInstallReport();
}

void Shutdown()
{
    if (g_hook)
    {
        g_hook.reset();   // SingleHook::~SingleHook() restores the original 38 bytes
        FlushInstructionCache(GetCurrentProcess(),
            reinterpret_cast<LPCVOID>(kWindowAddr), kWindowLen);
        IDDrawSurface::OutptTxt(
            "[CobDispatchTable] shutdown: original dispatch ladder restored.");
    }
}

} // namespace CobDispatchTable
